### ISSUE TITLE
Take 35c3 Apps' favorite lists

### ISSUE THREAD

**Issue by joker234** [mfherbst/down-frab-videos#15]
In the 35c3 Schedule App ([F-Droid](https://f-droid.org/de/packages/info.metadude.android.congress.schedule/) / [Play Store](https://play.google.com/store/apps/details?id=info.metadude.android.congress.schedule)) one can export so called favorite lists. These lists include e.g. a link to the frab webpage of the talk.

Currently a little script is extracting the talk-ids from the urls for me and I use them as input for down-frab-videos. It would be neat if the script would accept this list format natively.

Example file:
```
Opening Event
Donnerstag, 27. Dezember 2018 11:00, Adams

https://events.ccc.de/congress/2018/Fahrplan/events/9985.html

---


35C3 Infrastructure Review
Sonntag, 30. Dezember 2018 16:10, Borg

https://events.ccc.de/congress/2018/Fahrplan/events/9576.html

---

Closing Event
Sonntag, 30. Dezember 2018 17:10, Adams

https://events.ccc.de/congress/2018/Fahrplan/events/9986.html
```

**Comment by joker234** [comment]
Additionally, on this 35c3, there are other stages like [Chaos West](https://fahrplan.chaos-west.de/35c3chaoswest/schedule/) or [WikiPaka WG](https://cfp.verschwoerhaus.de/35c3/schedule/) that are using pretalx instead of frab. But both of them are also included in the above mentioned app and talks of them are also extracted like “regular” talks. It would be nice if the down-frab-videos had a possibility to combine these different stages (and backends) from the same event.

Example file:
```
Operation Mindfuck #2 - Computer, Kunst und Kuriositäten
Samstag, 29. Dezember 2018 23:00, WikiPakaWG Esszimmer

https://cfp.verschwoerhaus.de/35c3/talk/7CHZ9V

---

Court in the Akten
Sonntag, 30. Dezember 2018 12:30, Eliza

https://events.ccc.de/congress/2018/Fahrplan/events/9343.html
```

**Comment by mfherbst** [comment]
Definitely a great idea. Thanks for the pointer. Especially the parsing of the favourite list from the app should be easily achieved. The latter might require a little restructuring of the (admittedly rather bulky) code base.

**Comment by johnjohndoe** [comment]
@mfherbst The code which generates the favorites list can be found in [SimpleLectureFormat.java](https://github.com/EventFahrplan/EventFahrplan/blob/master/app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/SimpleLectureFormat.java).

**Comment by mfherbst** [comment]
Thanks for the pointer. I am a bit busy right now, but I'll look into it.
