### ISSUE TITLE
Script downloads German audio track files only

### ISSUE THREAD

**Issue by JanX2** [mfherbst/down-frab-videos#2]
Trying to investigate this further…

This file is downloaded
http://cdn.media.ccc.de/congress/2016/h264-hd/33c3-7861-deu-The_Universe_Is_Like_Seriously_Huge.mp4
instead of this one
http://cdn.media.ccc.de/congress/2016/h264-hd/33c3-7861-eng-deu-spa-The_Universe_Is_Like_Seriously_Huge_hd.mp4

**Comment by mfherbst** [comment]
Ah ... this is because I use the first matching link to a talkid, so aphabetically the German-only comes first. On it ;)

**Comment by mfherbst** [comment]
I made a quick and dirty fix for that. Ideally one would have an interface to select the audio track and also select to download only the file with the original audio. I'll add that if I have some time. But I hope this will do it for you now.

**Comment by JanX2** [comment]
Thanks! With the diff I have more than a snowball’s chance at figuring this out. :)

**Comment by mfherbst** [comment]
In my tests on commit 52ad20f this is fixed.
